### ISSUE TITLE
Questions about settings (gui1 and gui2)

### ISSUE THREAD

**Issue by HawkingJan** [JvanKatwijk/dab-rpi#8]
Hi,
I just started using your nice program and I've some questions. I hope that it is OK that I combine several thinks in one issue. If you want I can of course split them up but most likely you can answer most of them directly. Already many thanks for your program and your help.
I'm using dab-rpi-0.997 on my Raspberry 2 with a dabstick.

1) If I start the program using gui 1 and quit it after some time some settings are being saved (e.g. the channel) in ~/.dab-rpi.ini  but others (especially the audio output) are not saved and once I start the program again I've select the device again. Is there a reason for this? 

2) I like your mouse over explanations, however for the fine frequency offset and the coarse frequency offset there seem to be no explanation in the program it self. As these are the largest shown numbers I directly wanted to know what they are about (and found the answer on your homepage but not in the program).

3) Is there a reason that the program does not automatically at least scan for stations once it is started (currently I've to start the program, wait till it is started, press start button, wait till stations show up, select station)? 

4) In README.RPI it is written, that one should add latency=4 (or other values) in the ini file. However I'm not sure in which section of it ([General]?) As the effect is small (even without these settings the sound quality is OK but might get even better) and I don't see any output I'm not sure.

5) Sorry for the stupid question but what is "gain" in the context of your program?
Starting with gui1 I get "Supported gain values (29): 49.6 48.0 44.5 43.9 43.4 42.1 40.2 38.6 37.2 36.4 33.8 32.8 29.7 28.0 25.4 22.9 20.7 19.7 16.6 15.7 14.4 12.5 8.7 7.7 3.7 2.7 1.4 0.9 0.0"
and in the description of gui2 one can read "that "-G the gain to be applied on the device, in the range from 1 .. 100." 

6) Maybe add an example in the documentation on how to use  "-A the output channel" for GUI 2?
Initially I tried to use the channel (in numeric form) and not the name (as shown in GUI1).

**Comment by JvanKatwijk** [comment]
Your questions
1. The audio channel is not saved in the ini file, the reason is that with the combination portaudio/alsa under Linux, not in all cases the list of devices is the same. So - in principle it would be possible that an the name of an audio channel is saved for use the next time, while that next time the audio channel does not appear in the list.
2 true, 
3. the sdr-j-dab program has a scanning facility, the dab-rpi program does not. The gui_3 version, with the qml interface from AlbrechtL does have a scanning facility. Personally I do not think scanning facilities have added value. Implementation is not very complex.
4. The latency issue arose when I started with the RPI. I am using Arch on the RPI and the issue does not arise anymore (afaik). There are more issues that played earlier.
5. Gain depends on the device you are using, while most people that I speak use a dabstick, I myself very seldom use one, mine is mechanically pretty weak. I am using an airspy next to my laptop, and an sdrPlay connected to the RPI.
As reaction upon a couple of requests, the gains to be selected from are the gains as supported
by the device. The dabstick provides a table with valid gain values, expressed in dB, the sdrplay has attenuation settings from 0 .. 101, and the airspy has three sliders in the range from 0 .. 15.
Since in gui_2 (and gui_3) the widgets for the devices are invisible, a generic solution is applied: just a range from 0 .. 100, the selected value is then mapped upon an appropriate value supported by the device. So, if in gui_2 you select 75 and your device is a dabstick, then the value at three quarters of the table is selected as the real gain setting.
6. -A option: without specifying the -A option (and without previous settings), the "default" output device is selected, which in most Linux boxes works fine. As with the -P setting, a prefix of the name of the output channel, as appearing in the list channels, suffices. Lists are not necessarily the same in subsequenct invocations of the program, so mapping on a number is not the best solution.

I jope this answers the questions
best
